apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: userprofile
  name: userprofile-3
spec:
  replicas: 1
  selector:
    matchLabels:
      deploymentconfig: userprofile
      version: "3.0"
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        deploymentconfig: userprofile
        version: "3.0"
        app: userprofile
    spec:
      containers:
      - env:
        - name: USER_PROFILE_STYLE_ID
          value: "3"
        - name: POSTGRESQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: database-name
              name: userprofile-postgresql
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: userprofile-postgresql
        - name: POSTGRESQL_SERVICE_HOST
          value: userprofile-postgresql
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: userprofile-postgresql
        - name: POSTGRESQL_SERVICE_PORT
          value: "5432"
        image: %USER_PROFILE_IMAGE_URI%:3.0
        imagePullPolicy: Always
        name: userprofile
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
