/*
 * CandV
 * The CandV API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Item
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-10-26T12:35:23.449-04:00")
public class Item {
  @SerializedName("timestamp")
  private String timestamp = null;

  @SerializedName("raw")
  private String raw = null;

  public Item timestamp(String timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * A timestamp of when the item was put in the clipboard as ISO 8601 e.g.: 2014-09-08T08:02:17-05:00
   * @return timestamp
  **/
  @ApiModelProperty(value = "A timestamp of when the item was put in the clipboard as ISO 8601 e.g.: 2014-09-08T08:02:17-05:00")
  public String getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(String timestamp) {
    this.timestamp = timestamp;
  }

  public Item raw(String raw) {
    this.raw = raw;
    return this;
  }

   /**
   * The raw string of the item on the clipboard
   * @return raw
  **/
  @ApiModelProperty(value = "The raw string of the item on the clipboard")
  public String getRaw() {
    return raw;
  }

  public void setRaw(String raw) {
    this.raw = raw;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Item item = (Item) o;
    return Objects.equals(this.timestamp, item.timestamp) &&
        Objects.equals(this.raw, item.raw);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timestamp, raw);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Item {\n");
    
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    raw: ").append(toIndentedString(raw)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

