/*
 * CandV
 * The CandV API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Error;
import io.swagger.client.model.Item;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * 
     *
     * Returns the JSON for the entire clipboard
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void boardsBoardIdGetTest() throws ApiException {
        Long boardId = null;
        List<Item> response = api.boardsBoardIdGet(boardId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Removes the item from this board
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void boardsBoardIdItemsItemIdDeleteTest() throws ApiException {
        Long boardId = null;
        Long itemId = null;
        api.boardsBoardIdItemsItemIdDelete(boardId, itemId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Returns the JSON for a specific item in a board
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void boardsBoardIdItemsItemIdGetTest() throws ApiException {
        Long boardId = null;
        Long itemId = null;
        Item response = api.boardsBoardIdItemsItemIdGet(boardId, itemId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Add an item into this board
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void boardsBoardIdItemsPostTest() throws ApiException {
        Long boardId = null;
        api.boardsBoardIdItemsPost(boardId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Add a new board
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void boardsPostTest() throws ApiException {
        api.boardsPost();

        // TODO: test validations
    }
    
}
