# Rule for boards service servers to only accept mTLS + JWT traffic
#
# You also need to replace the domain with your SSO path and domain
# sed "s|replace-me-sso|keycloak-sso-shared.apps.cluster.domain.com|" ./policy-boards-jwt.yaml
#
apiVersion: "security.istio.io/v1beta1"
kind: RequestAuthentication
metadata:
  name: "boards-jwt"
spec:
  selector:
    matchLabels:
      app: boards
      deploymentconfig: boards
  jwtRules:
  - issuer: https://%SSO_SVC%/auth/realms/microservices-demo
    jwksUri: https://%SSO_SVC%/auth/realms/microservices-demo/protocol/openid-connect/certs
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: boards-shared
spec:
  selector:
    matchLabels:
      app: boards
      deploymentconfig: boards
  rules:
  - from:
    - source:
        requestPrincipals: ["*"]
    to:
    - operation:
        methods: ["GET"]