apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: demo-user
  labels:
    app.realm: microservices-demo
  namespace: sso-shared
spec:
  user:
    username: demo
    firstName: Demo
    lastName: Demoer
    email: demo@redhatgov.io
    enabled: true
    emailVerified: false
    realmRoles:
      - "offline_access"
      - "member"
  realmSelector:
    matchLabels:
      app.realm: microservices-demo
