#
# You will need to replace the rootUrl below with your proper path
# DONT USE THIS FOR PRODUCTION - IT'S VERY OPEN
#
apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: microservices-demo-keycloakrealm
  namespace: sso-shared
  labels:
    app: sso
    app.realm: microservices-demo
spec:
  realm:
    id: microservices-demo
    realm: microservices-demo
    enabled: true
    displayName: Microservices Demo
    webOrigins:
      - "*"
    roles:
      realm:
      - name: cool-kids
        description: cool kids are cool
        clientRole: false
      client:
        client-app:
        - name: client-app-member
          description: for members of the client app
          clientRole: true
    clients:
      - description: "Microservices demo application UI clients"
        clientId: client-app
        publicClient: true
        redirectUris:
        - "http://istio-ingressgateway-istio-system.apps.cluster.domain.com/*"
        adminUrl: "http://istio-ingressgateway-istio-system.apps.cluster.domain.com/"
        directAccessGrantsEnabled: true
        webOrigins:
          - "*"
          - "+"
  instanceSelector:
    matchLabels:
      app: sso
