apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: workshop-install
spec:
  proxy:
    networking:
      trafficControl:
        outbound:
          policy: REGISTRY_ONLY
  tracing:
    type: Jaeger
  addons:
    jaeger:
      name: jaeger
    grafana:
      enabled: true
    kiali:
      name: kiali
      enabled: true
    prometheus:
      enabled: true
